//! levels.rs
//!
//! This module is a store for level data

extern crate colored;

use crate::game::object::Object;
use colored::*;
//use crate::game::monster::Monster;

///
/// Game contains different levels and each level has it's own map, objects and exit points
///
pub struct Level<'a> {
    pub level_name: &'a str,
    pub player_start_x: usize,
    pub player_start_y: usize,
    pub map_chars: Vec<&'a str>,
    pub map_colors: Vec<&'a str>,
    pub map_color_key: Vec<(char, &'a str)>,
    // map_bools is adding bits: 1 = blocked, 2 = visited
    pub map_bools: Vec<&'a str>,
    pub objects: Vec<Object>,
    //    pub monsters: Vec<Monster>,
}

///
/// Function to create maps for each levels on the game
/// @level_number : game level number
/// @returns : level
///
pub fn level(level_number: usize) -> Level<'static> {
    match level_number {
        1 => Level {
            level_name: "Level 1",
            player_start_x: 5,
            player_start_y: 5,
            map_chars: [
                "..................~┌──────",
                ".................~%│......",
                "................~%~│......",
                ".................~%│......",
                "..........................",
                ".................~~│......",
                "................~%~│......",
                ".................~%│......",
                "..................~└──────",
            ]
            .to_vec(),
            map_colors: [
                "                  brrrrrrr",
                "                 bbr      ",
                "                bbbr      ",
                "                 bbr      ",
                "                          ",
                "                 bbr      ",
                "                bbbr      ",
                "                 bbr      ",
                "                  brrrrrrr",
            ]
            .to_vec(),
            map_color_key: [('r', "red"), ('b', "blue"), (' ', "green")].to_vec(),
            map_bools: [
                "22222222222222222233333333",
                "22222222222222222333222222",
                "22222222222222223333222222",
                "22222222222222222333222222",
                "22222222222222222222222222",
                "22222222222222222333222222",
                "22222222222222223333222222",
                "22222222222222222333222222",
                "22222222222222222233333333",
            ]
            .to_vec(),
            objects: [
                Object {
                    x: 6,
                    y: 6,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "A completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 1,
                    id: 1,
                },
                Object {
                    x: 6,
                    y: 7,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Another completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 2,
                },
                Object {
                    x: 6,
                    y: 8,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Another completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 2,
                },
                Object {
                    x: 7,
                    y: 8,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Another completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 2,
                },
                Object {
                    x: 7,
                    y: 7,
                    print: '⑈',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Key".to_string(),
                    holdable: true,
                    color: "cyan".to_string(),
                    print_colored: '⑈'.to_string().color("cyan"),
                    paired_item: "".to_string(),
                    score: 3,
                    id: 13,
                },
                Object {
                    x: 8,
                    y: 7,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Another completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 2,
                },
                Object {
                    x: 7,
                    y: 6,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Another completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 2,
                },
                Object {
                    x: 4,
                    y: 3,
                    print: 'Γ',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Pickaxe".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: 'Γ'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 3,
                    id: 3,
                },
                Object {
                    x: 4,
                    y: 24,
                    print: 'E',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Exit".to_string(),
                    holdable: false,
                    color: "pink".to_string(),
                    print_colored: 'E'.to_string().color("pink"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 99,
                },
                Object {
                    x: 4,
                    y: 19,
                    print: '█',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Door".to_string(),
                    holdable: true,
                    color: "magenta".to_string(),
                    print_colored: '█'.to_string().color("magenta"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 80,
                },
            ]
            .to_vec(),
        },
        2 => Level {
            level_name: "Level 2",
            player_start_x: 4,
            player_start_y: 3,
            map_chars: [
                "┌────────┬──┬───────┬────┐",
                "│........│..│.......│....│",
                "│........│..........│....│",
                "│........│..│.......└.───┤",
                "│........└.─┤............│",
                "│........................│",
                "│........................│",
                "│........................│",
                "└───────────┴────────────┘",
            ]
            .to_vec(),
            map_colors: [
                "rrrrrrrrrrrrrrrrrrrrrrrrrr",
                "r        r  r       r    r",
                "r        r          r    r",
                "r        r  r       r rrrr",
                "r        r rr            r",
                "r                        r",
                "r                        r",
                "r                        r",
                "rrrrrrrrrrrrrrrrrrrrrrrrrr",
            ]
            .to_vec(),
            map_color_key: [('r', "red"), ('b', "blue"), (' ', "green")].to_vec(),
            map_bools: [
                "33333333333333333333333333",
                "32222222232232222222322223",
                "32222222232222222222322223",
                "32222222232232222222323333",
                "32222222232332222222222223",
                "32222222222222222222222223",
                "32222222222222222222222223",
                "32222222222222222222222223",
                "33333333333333333333333333",
            ]
            .to_vec(),
            objects: [
                Object {
                    x: 4,
                    y: 10,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "A completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 1,
                },
                Object {
                    x: 2,
                    y: 12,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Another completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 2,
                },
                Object {
                    x: 7,
                    y: 1,
                    print: 'Γ',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Pickaxe".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: 'Γ'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 20,
                    id: 3,
                },
                Object {
                    x: 5,
                    y: 12,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 6,
                    y: 12,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 7,
                    y: 12,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 10,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 2,
                    y: 11,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 1,
                    y: 10,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 1,
                    y: 11,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 3,
                    y: 21,
                    print: '◙',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Iron door".to_string(),
                    holdable: true,
                    color: "magenta".to_string(),
                    print_colored: '◙'.to_string().color("magenta"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 81,
                },
                Object {
                    x: 1,
                    y: 1,
                    print: '⑈',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Key".to_string(),
                    holdable: true,
                    color: "cyan".to_string(),
                    print_colored: '⑈'.to_string().color("cyan"),
                    paired_item: "".to_string(),
                    score: 3,
                    id: 13,
                },
                Object {
                    x: 2,
                    y: 24,
                    print: 'E',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Exit".to_string(),
                    holdable: false,
                    color: "pink".to_string(),
                    print_colored: 'E'.to_string().color("pink"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 99,
                },
            ]
            .to_vec(),
        },
        3 => Level {
            level_name: "Level 3",
            player_start_x: 5,
            player_start_y: 5,
            map_chars: [
                "┌────────┬─┬─┬─┬───┬─┐≈≈≈~",
                "│........│.│.│.│...│.│≈†≈~",
                "│........└.┴.┴.┘...│.│≈≈≈%",
                "│..................│.│≈≈~%",
                "│....................│≈~%~",
                "│....................│≈≈~%",
                "│....................│≈~%~",
                "│....................│≈≈≈%",
                "└────────────────────┘≈≈≈≈",
            ]
            .to_vec(),
            map_colors: [
                "rrrrrrrrrrrrrrrrrrrrrr   b",
                "r        r r r r   r r w b",
                "r        r r r r   r r   b",
                "r                  r r  bb",
                "r                    r bbb",
                "r                    r  bb",
                "r                    r bbb",
                "r                    r   b",
                "rrrrrrrrrrrrrrrrrrrrrr    ",
            ]
            .to_vec(),
            map_color_key: [('w', "white"), ('r', "red"), ('b', "blue"), (' ', "green")].to_vec(),
            map_bools: [
                "33333333333333333333332223",
                "32222222232323232223232233",
                "32222222232323232223232233",
                "32222222222222222223232333",
                "32222222222222222222232333",
                "32222222222222222222232233",
                "32222222222222222222232333",
                "32222222222222222222232223",
                "33333333333333333333332222",
            ]
            .to_vec(),
            objects: [
                Object {
                    x: 1,
                    y: 12,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 2,
                    y: 5,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 2,
                    y: 4,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 1,
                    y: 5,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 1,
                    y: 4,
                    print: '≌',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Water".to_string(),
                    holdable: false,
                    color: "blue".to_string(),
                    print_colored: '≌'.to_string().color("blue"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 5,
                },
                Object {
                    x: 5,
                    y: 17,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 6,
                    y: 17,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 7,
                    y: 17,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 17,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 3,
                    y: 17,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 17,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 15,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 5,
                    y: 15,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 6,
                    y: 15,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 9,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 5,
                    y: 9,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 6,
                    y: 9,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 7,
                    y: 9,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 3,
                    y: 4,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 5,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 6,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 5,
                    y: 6,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 6,
                    y: 6,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 1,
                    y: 6,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 6,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 3,
                    y: 6,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 3,
                    y: 13,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 3,
                    y: 3,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 3,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 3,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 1,
                    y: 3,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 3,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 1,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 6,
                    y: 12,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 5,
                    y: 12,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 4,
                    y: 12,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 1,
                    y: 10,
                    print: 'Б',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Old man".to_string(),
                    holdable: true,
                    color: "purple".to_string(),
                    print_colored: 'Б'.to_string().color("purple"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 85,
                },
                Object {
                    x: 1,
                    y: 14,
                    print: 'B',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Bread".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: 'B'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 86,
                },
                Object {
                    x: 1,
                    y: 20,
                    print: 'E',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Exit".to_string(),
                    holdable: false,
                    color: "pink".to_string(),
                    print_colored: 'E'.to_string().color("pink"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 99,
                },
                Object {
                    x: 3,
                    y: 20,
                    print: '□',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Pit".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '□'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 87,
                },
                Object {
                    x: 1,
                    y: 1,
                    print: '⑈',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Key".to_string(),
                    holdable: true,
                    color: "cyan".to_string(),
                    print_colored: '⑈'.to_string().color("cyan"),
                    paired_item: "".to_string(),
                    score: 3,
                    id: 13,
                },
                Object {
                    x: 2,
                    y: 14,
                    print: '◙',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Iron door".to_string(),
                    holdable: true,
                    color: "magenta".to_string(),
                    print_colored: '◙'.to_string().color("magenta"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 81,
                },
            ]
            .to_vec(),
        },
        // Test purpose
        100 => Level {
            level_name: "Test Level",
            player_start_x: 1,
            player_start_y: 1,
            map_chars: ["┌───┐", "│...│", "│...│", "└───┘"].to_vec(),
            map_colors: ["rrrrr", "r   r", "r   r", "rrrrr"].to_vec(),
            map_color_key: [('r', "red"), ('b', "blue"), (' ', "green")].to_vec(),
            map_bools: ["33333", "32223", "32223", "33333"].to_vec(),
            objects: [
                Object {
                    x: 2,
                    y: 3,
                    print: '0',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "A completely average boulder.".to_string(),
                    holdable: false,
                    color: "white".to_string(),
                    print_colored: '0'.to_string().color("white"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 1,
                },
                Object {
                    x: 1,
                    y: 2,
                    print: 'Γ',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Pickaxe".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: 'Γ'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 20,
                    id: 3,
                },
                Object {
                    x: 1,
                    y: 1,
                    print: '*',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Potion".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: '*'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 20,
                    id: 3,
                },
            ]
            .to_vec(),
        },

        // Test purpose
        101 => Level {
            level_name: "Test Level",
            player_start_x: 1,
            player_start_y: 1,
            map_chars: ["┌─────┐", "│...│", "│...│", "└─────┘"].to_vec(),
            map_colors: ["rrrrrrr", "r   r", "r   r", "rrrrrrr"].to_vec(),
            map_color_key: [('r', "red"), ('b', "blue"), (' ', "green")].to_vec(),
            map_bools: ["3333333", "32223", "32223", "3333333"].to_vec(),
            objects: [
                Object {
                    x: 2,
                    y: 3,
                    print: 'Ж',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Fire".to_string(),
                    holdable: false,
                    color: "red".to_string(),
                    print_colored: 'Ж'.to_string().color("red"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 4,
                },
                Object {
                    x: 2,
                    y: 1,
                    print: '█',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Door".to_string(),
                    holdable: true,
                    color: "magenta".to_string(),
                    print_colored: '█'.to_string().color("magenta"),
                    paired_item: "".to_string(),
                    score: 0,
                    id: 80,
                },
                Object {
                    x: 1,
                    y: 2,
                    print: 'Γ',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Pickaxe".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: 'Γ'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 20,
                    id: 3,
                },
                Object {
                    x: 1,
                    y: 1,
                    print: '*',
                    attri: 0,
                    mat: 0,
                    status: 0,
                    quantity: 1,
                    descr: "Potion".to_string(),
                    holdable: true,
                    color: "yellow".to_string(),
                    print_colored: '*'.to_string().color("yellow"),
                    paired_item: "".to_string(),
                    score: 20,
                    id: 3,
                },
            ]
            .to_vec(),
        },

        _ => panic!("call to initialize undefined level number in init_level()"),
    }
}
